version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
    environment:
      - DB_CONNECT=mongodb://mongodb:27017/store_ms
  authserver:
    build:
      context: ./authserver
      dockerfile: Dockerfile
    ports:
      - '4001:4001'
    depends_on:
      - mongodb
    environment:
      - DB_CONNECT=mongodb://mongodb:27017/store_ms
      - TOKEN_SECRET=NJD3402
      - REDIS_PORT=6379
      - REDIS_HOST=127.0.0.1
  admin_page:
    build:
      context: ./admin_page
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  order_consumer:
    build:
      context: ./socket/order-consumer
      dockerfile: Dockerfile
    ports:
      - '5002:5002'
    depends_on:
      - rabbitmq
  product_consumer:
    build:
      context: ./socket/product-consumer
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
    depends_on:
      - rabbitmq
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - '5672:5672'
      - '15672:15672'
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - '80:80'
    depends_on:
      - server
      - authserver
      - admin_page
      - users
      - order_consumer
      - product_consumer
      - redis
      - rabbitmq
