version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
    environment:
      - DB_CONNECT=mongodb://mongodb:27017/store_ms
      - PORT=4000
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    volumes: 
      - ./server:/app
  authserver:
    build:
      context: ./authserver
      dockerfile: Dockerfile
    ports:
      - '4001:4001'
    depends_on:
      - mongodb
    environment:
      - DB_CONNECT=mongodb://mongodb:27017/store_ms
      - TOKEN_SECRET=NJD3402
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - PORT=4001
    volumes:
      - ./authserver:/app
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - server
      - authserver
    environment:
      - VUE_APP_PRODUCTION_MODE=true
      - VUE_APP_PRODUCTION_HOST=http://localhost
    volumes:
      - ./admin:/app
  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - server
      - authserver
      - orderconsumer
    environment:
      - VUE_APP_PRODUCTION_MODE=true
      - VUE_APP_PRODUCTION_HOST=http://localhost
      - VUE_APP_ORDERCONSUMER_BASE=http://orderconsumer:5002
    volumes:
      - ./users:/app
  orderconsumer:
    build:
      context: ./socket/orderconsumer
      dockerfile: Dockerfile
    ports:
      - '5002:5002'
    depends_on:
      - rabbitmq
    volumes:
      - ./socket/orderconsumer:/app
  # productconsumer:
  #   build:
  #     context: ./socket/productconsumer
  #     dockerfile: Dockerfile
  #   ports:
  #     - '5001:5001'
  #   depends_on:
  #     - rabbitmq
  #   volumes:
  #     - ./socket/productconsumer:/app
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - '5672:5672'
      - '15672:15672'
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/storems.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - server
      - authserver
      - admin
      - users
      - orderconsumer
      - productconsumer
      - redis
      - rabbitmq
